[build-system]
requires = [
    "setuptools >= 68.2.2",
    "setuptools-scm[toml] >= 7.1.0",
    "wheel >= 0.41.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "httpx_tutorial"
version = "0.1.0"
dependencies = [
    "httpx",
]
